[0m23:06:31.291953 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f208e03f1d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f208ddf1b50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f208e03d710>]}


============================== 23:06:31.294093 | 40655846-b6d7-4132-8fac-aa510d325b1f ==============================
[0m23:06:31.294093 [info ] [MainThread]: Running with dbt=1.5.0
[0m23:06:31.294650 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/tanay/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m23:06:46.199889 [debug] [MainThread]: Starter project path: /home/tanay/repos/dbt-intro/venv/lib/python3.11/site-packages/dbt/include/starter_project
[0m23:06:50.631659 [error] [MainThread]: Encountered an error:
[Errno 20] Not a directory: '/home/tanay/.dbt/profiles.yml'
[0m23:06:50.633352 [error] [MainThread]: Traceback (most recent call last):
  File "/home/tanay/repos/dbt-intro/venv/lib/python3.11/site-packages/dbt/cli/requires.py", line 86, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tanay/repos/dbt-intro/venv/lib/python3.11/site-packages/dbt/cli/requires.py", line 71, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tanay/repos/dbt-intro/venv/lib/python3.11/site-packages/dbt/cli/main.py", line 459, in init
    results = task.run()
              ^^^^^^^^^^
  File "/home/tanay/repos/dbt-intro/venv/lib/python3.11/site-packages/dbt/task/init.py", line 305, in run
    self.create_profile_from_target(adapter, profile_name=project_name)
  File "/home/tanay/repos/dbt-intro/venv/lib/python3.11/site-packages/dbt/task/init.py", line 190, in create_profile_from_target
    self.create_profile_from_sample(adapter, profile_name)
  File "/home/tanay/repos/dbt-intro/venv/lib/python3.11/site-packages/dbt/task/init.py", line 97, in create_profile_from_sample
    with open(profiles_filepath, "w") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotADirectoryError: [Errno 20] Not a directory: '/home/tanay/.dbt/profiles.yml'

[0m23:06:50.634188 [debug] [MainThread]: Command `dbt init` failed at 23:06:50.634033 after 19.34 seconds
[0m23:06:50.634625 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f208ddf0a90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f208ddc0190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f208ddc01d0>]}
[0m23:06:50.635062 [debug] [MainThread]: Flushing usage events
[0m23:07:04.259968 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6a58f3e210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6a58f22890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6a58deb350>]}


============================== 23:07:04.262363 | 740f0835-3c48-4c90-a2db-0c0fb73e53fc ==============================
[0m23:07:04.262363 [info ] [MainThread]: Running with dbt=1.5.0
[0m23:07:04.262918 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/tanay/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m23:07:09.431449 [info ] [MainThread]: A project called dbt_intro already exists here.
[0m23:07:09.434377 [debug] [MainThread]: Command `dbt init` succeeded at 23:07:09.433818 after 5.18 seconds
[0m23:07:09.435878 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6a5ca17590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6a58f22fd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6a58e0db90>]}
[0m23:07:09.437452 [debug] [MainThread]: Flushing usage events
[0m13:26:02.693724 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6c8b779750>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6c8bdc4250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6c8b76b010>]}


============================== 13:26:02.695795 | 24ade294-565c-4e90-bf9c-54c1d8acbcc0 ==============================
[0m13:26:02.695795 [info ] [MainThread]: Running with dbt=1.5.0
[0m13:26:02.696309 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/home/tanay/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m13:26:02.696669 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/tanay/repos/dbt-intro/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:26:02.697230 [debug] [MainThread]: Command `dbt run` failed at 13:26:02.697136 after 0.01 seconds
[0m13:26:02.697584 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6c8b27a290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6c8b256990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6c8ba7d4d0>]}
[0m13:26:02.697871 [debug] [MainThread]: Flushing usage events
